### ISSUE TITLE
Production build failing when prerendering buyers page

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2123]
**Describe the bug**

The following error is occurring in the build logs when building `regen-www`:

```
10:19:15 AM: web-www: Error occurred prerendering page /buyers. Read more: https://nextjs.org/docs/messages/prerender-error
10:19:15 AM: web-www: ApolloError: Cannot query field image on type Project.
10:19:15 AM: web-www: Cannot query field location on type Project.
10:19:15 AM: web-www: Cannot query field area on type Project. Did you mean _rev?
10:19:15 AM: web-www: Cannot query field areaUnit on type Project.
10:19:15 AM: web-www: Cannot query field program on type CreditClass.
10:19:15 AM: web-www:     at new ApolloError (/opt/build/repo/node_modules/@apollo/client/errors/errors.cjs:31:28)
10:19:15 AM: web-www:     at /opt/build/repo/node_modules/@apollo/client/core/core.cjs:1947:47
10:19:15 AM: web-www:     at both (/opt/build/repo/node_modules/@apollo/client/utilities/utilities.cjs:1239:53)
10:19:15 AM: web-www:     at /opt/build/repo/node_modules/@apollo/client/utilities/utilities.cjs:1232:72
10:19:15 AM: web-www:     at new Promise (<anonymous>)
10:19:15 AM: web-www:     at Object.then (/opt/build/repo/node_modules/@apollo/client/utilities/utilities.cjs:1232:24)
10:19:15 AM: web-www:     at Object.next (/opt/build/repo/node_modules/@apollo/client/utilities/utilities.cjs:1240:49)
10:19:15 AM: web-www:     at notifySubscription (/opt/build/repo/node_modules/zen-observable/lib/Observable.js:135:18)
10:19:15 AM: web-www:     at onNotify (/opt/build/repo/node_modules/zen-observable/lib/Observable.js:179:3)
10:19:15 AM: web-www:     at SubscriptionObserver.next (/opt/build/repo/node_modules/zen-observable/lib/Observable.js:235:7)
```

**To Reproduce**

- https://app.netlify.com/sites/regen-website/deploys/6509d72414afff260d3abec0

**Additional context**

This occurred before the `regen-server` production deployment, after clearing the cache and attempting to rebuild, and then again after the `regen-server` production deployment and clearing the cache and attempting to rebuild.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
This was an issue with a failed deployment in sanity that has been resolved.
